language: android
sudo: required
android:
  components:
    - tools
    - build-tools-23.0.3
    - build-tools-22.0.1
    - android-23
    - android-22
    - extra-android-support
    - extra-android-m2repository
  licenses:
    - 'android-sdk-license-.+'
    - '.*intel.+'
addons:
  apt:
    packages:
    - tor
before_install:
  - wget https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.1.1-linux-x86_64.tar.bz2 -O - | tar xfj -
  - echo 'deb http://us-central1.gce.archive.ubuntu.com/ubuntu/ trusty-backports main universe' | sudo tee /etc/apt/sources.list.d/trusty-backports.list
  - "echo -e 'Package: *\nPin: release a=trusty-backports\nPin-Priority: 100' | sudo tee /etc/apt/preferences.d/trusty-backports"
  - sudo apt-get update
  - sudo apt-get install -t trusty-backports torsocks
  - npm install
  - until bash -c 'torsocks phantomjs-2.1.1-linux-x86_64/bin/phantomjs adblock.js > AdBlock.java'; do echo retry; done
  - mv AdBlock.java app/src/main/java/acr/browser/lightning/utils/AdBlock.java
  - chmod +x gradlew
  - git submodule update --init --recursive
  - openssl aes-256-cbc -K $encrypted_5a432c4ab535_key -iv $encrypted_5a432c4ab535_iv -in my-release-key.keystore.enc -out my-release-key.keystore -d
  - echo "RELEASE_STORE_FILE=../my-release-key.keystore" > gradle.properties
  - echo "RELEASE_STORE_PASSWORD=$KEYSTORE_PASS" >> gradle.properties
  - echo "RELEASE_KEY_ALIAS=alias_name" >> gradle.properties
  - echo "RELEASE_KEY_PASSWORD=$KEYSTORE_PASS" >> gradle.properties
install:
  - ./gradlew
script:
  - ./gradlew assembleRelease --stacktrace
before_deploy:
  - cd $TRAVIS_BUILD_DIR
  - echo version > $(git describe --abbrev=40 --always)
  - echo -e "machine github.com\nlogin galeksandrp\npassword $GITHUB_TOKEN" >> ~/.netrc
  - git tag deploy-$(git describe --always) $TRAVIS_COMMIT || true
  - git push origin deploy-$(git describe --always)
deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  skip_cleanup: true
  file: 
  - app/build/outputs/apk/*
  file_glob: true
  overwrite: true
  on:
    all_branches: true
branches:
  except:
    - /^deploy-.*$/
notifications:
  email: false
