language: android
sudo: false
android:
  components:
    - tools
    - build-tools-23.0.3
    - build-tools-22.0.1
    - android-23
    - android-22
    - extra-android-support
    - extra-android-m2repository
  licenses:
    - 'android-sdk-license-.+'
    - '.*intel.+'
before_install:
  - chmod +x gradlew
  - git submodule update --init --recursive
install:
  - ./gradlew
script:
  - ./gradlew assembleDebug --stacktrace
before_deploy:
  - cd $TRAVIS_BUILD_DIR
  - echo version > $(git describe --abbrev=40 --always)
  - echo -e "machine github.com\nlogin galeksandrp\npassword $GITHUB_TOKEN" >> ~/.netrc
  - git tag deploy-$(git describe --always) $TRAVIS_COMMIT || true
  - git push --tags
deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  skip_cleanup: true
  file: 
  - app/build/outputs/apk/app-lightningLite-debug.apk
  - app/build/outputs/apk/app-lightningLite-debug-unaligned.apk
  - app/build/outputs/apk/app-lightningPlus-debug.apk
  - app/build/outputs/apk/app-lightningPlus-debug-unaligned.apk
  overwrite: true
  on:
    all_branches: true
branches:
  except:
    - /^deploy-.*$/
notifications:
  email: false
